### PR TITLE
Pivot table sorting amends

### PR DESCRIPTION
**Pull request by leehart**
Fyxes https://github.com/wtchg-kwiatkowski/observatory-web/issues/318

### CODE REVIEW

**Comment by leehart** [comment]
Also fyxes wtchg-kwiatkowski/observatory-web#231

**Comment by leehart** [comment]
Also fyxes wtchg-kwiatkowski/observatory-web#232

**Comment by leehart** [comment]
Closing temporarily to resolve problem with https://github.com/wtchg-kwiatkowski/observatory-web/issues/231

**Comment by benjeffery** [comment]
I got a conflict here - I'm merging oldest to newest so thought it would be ok... you want me to fix or do you know what this is?

**Comment by leehart** [comment]
It's probably because the previous PR merge with master caused a conflict. I'll resolve.... just a sec.

**Comment by leehart** [comment]
ugh, that was tricky

**Pull request merged**
