### PR TITLE
"Display" tabs again

### PR DESCRIPTION
**Pull request by benjeffery**
I know. You're feeling a sense of strange deja-vu as you stare at the code below. 

No, you say, it cannot be! Surely not! 

But yes. I _think_ this is the end of the matter, but please have a go before merging.

### CODE REVIEW

**Comment by leehart** [comment]
Haven't found any showstoppers yet :-)
+ fixes the flying label bug

- still get a flickering with modals (poss. unrelated) 
- sidebar boundary falls short when expanded (prob. style)
- popups are broken (on master too) so can't check that yet

**Comment by benjeffery** [comment]
Ok, will fix those others first

**Comment by leehart** [comment]
- expanded sidebar gets yucky scrollbars on Map Composer (prob. MapActions fault)

**Comment by benjeffery** [comment]
Scrollbars and popups fixed

**Comment by benjeffery** [comment]
Just that map scrollbar left

**Comment by leehart** [comment]
The scrollbar appearing to the right of the sidebar, mixing with right-hand content, happens in all cases where sidebar content is longer than the viewport.

**Comment by leehart** [comment]
Symptom or unrelated glitch?

tree

**Comment by benjeffery** [comment]
Ok, sidebar scrollbar fixed.
The zoomed in tree is phylocanvas not properly resizing...

**Pull request merged**
